app:
  name: Crytocoin Price indicator
  description: An Ubuntu desktop indicator displays prices of Bitcoin, Ethereum, Litecoin etc.
  url: https://github.com/techstar-inc/cryptocoin-price
  version: "0.0.4"

author:
  name: Techstar, Inc.
  email: toroo.byamba@gmail.com
  copyright: Copyright (C) 2017 Techstar, Inc.
